spring.application.name=spring-rag-demo

server.port=${PORT:8080}

# PostgreSQL Configuration

spring.datasource.url=postgresql://rag_user:ltaDDo0gGV1HHArsqwka003oD4B6rVvA@dpg-d7ffujfaqgkc739pqq2g-a.ohio-postgres.render.com/rag_db_v3md
spring.datasource.username=rag_user
spring.datasource.password=ltaDDo0gGV1HHArsqwka003oD4B6rVvA

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.ai.vectorstore.pgvector.initialize-schema=false

server.port=${PORT:8080}
# Spring AI OpenAI Configuration
spring.ai.openai.base-url=${OPENAI_BASE_URL:http://localhost:1234}
spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.embedding.options.model=text-embedding-nomic-embed-text-v2-moe
spring.ai.openai.embedding.options.dimensions=768

spring.ai.openai.chat.base-url=${OPENAI_CHAT_BASE_URL:https://openrouter.ai}
spring.ai.openai.chat.completions-path=/api/v1/chat/completions
spring.ai.openai.chat.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=google/gemini-2.5-flash
spring.ai.openai.chat.options.max-tokens=1024

# Spring SQL initialization for PostgreSQL
# Flyway is used for schema migration in deployment.
# In production, ensure the DB user can run CREATE EXTENSION and CREATE TABLE.
spring.sql.init.mode=never
spring.flyway.enabled=true

# Spring AI PgVector Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
spring.ai.vectorstore.pgvector.schema-validation=true
spring.ai.vectorstore.pgvector.table-name=vector_store