# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# NVIDIA - Embedding (1024 dimensions)
spring.ai.openai.base-url=https://integrate.api.nvidia.com
spring.ai.openai.api-key=${NVIDIA_API_KEY}
spring.ai.openai.embedding.options.model=nvidia/llama-3.2-nv-embedqa-1b-v2
spring.ai.openai.embedding.options.dimensions=1024

# Groq - Chat
spring.ai.openai.chat.base-url=https://api.groq.com/openai
spring.ai.openai.chat.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.openai.chat.options.temperature=0
spring.ai.openai.chat.options.max-tokens=80

# PgVector
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.schema-validation=false
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.table-name=vector_store

# Server
server.port=${PORT:8080}